# Generated by Django 4.2.3 on 2024-04-10 20:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("text", models.TextField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Clothing Store", max_length=200)),
                ("desc", models.TextField(null=True)),
                (
                    "email",
                    models.EmailField(
                        default="clothingstore@gmail.com", max_length=254
                    ),
                ),
                ("phone", models.CharField(max_length=20, null=True)),
                ("address", models.CharField(max_length=500, null=True)),
                (
                    "working_hours",
                    models.CharField(default="Mon - Fri: 8AM - 10PM", max_length=200),
                ),
                (
                    "maps_url",
                    models.URLField(
                        default="https://www.google.com/maps?q=10+Broad+Street,+Lagos,+Nigeria&z=13&ie=UTF8&iwloc=&output=embed"
                    ),
                ),
                (
                    "fb",
                    models.URLField(
                        default="https://www.facebook.com", verbose_name="Facebook"
                    ),
                ),
                (
                    "ig",
                    models.URLField(
                        default="https://www.instagram.com/", verbose_name="Instagram"
                    ),
                ),
                (
                    "tw",
                    models.URLField(
                        default="https://www.twitter.com/", verbose_name="Twitter"
                    ),
                ),
                (
                    "ln",
                    models.URLField(
                        default="https://www.linkedin.com/", verbose_name="Linkedin"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
