# Generated by Django 4.2.3 on 2024-01-14 04:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "image",
                    models.ImageField(upload_to="portfolio", verbose_name="Image"),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "github_url",
                    models.URLField(blank=True, null=True, verbose_name="Github URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, null=True, verbose_name="Linkedin URL"),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, null=True, verbose_name="Twitter URL"),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, null=True, verbose_name="Facebook URL"),
                ),
                (
                    "instagram_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Instagram URL"
                    ),
                ),
                (
                    "behance_url",
                    models.URLField(blank=True, null=True, verbose_name="Behance URL"),
                ),
            ],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolios",
            },
        ),
    ]
