# Generated by Django 4.2.3 on 2024-04-10 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "image",
                    models.ImageField(upload_to="portfolio", verbose_name="Image"),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="URL")),
                (
                    "github_url",
                    models.URLField(blank=True, null=True, verbose_name="Github URL"),
                ),
                (
                    "medium_url",
                    models.URLField(blank=True, null=True, verbose_name="Medium URL"),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.DeleteModel(
            name="Portfolio",
        ),
    ]
