# Generated by Django 4.2.3 on 2024-04-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_project_delete_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="project", verbose_name="Image"),
        ),
    ]
